/*
 *  ____ ___ ____   ____   powered by   _
 * / ___|_ _| __ ) / ___|_ __ ___  __ _| |_ ___  _ __
 * \___ \| ||  _ \| |   | '__/ _ \/ _` | __/ _ \| '__|
 *  ___) | || |_) | |___| | |  __/ (_| | || (_) | |
 * |____/___|____/ \____|_|  \___|\__,_|\__\___/|_|
 * Generated by the SIBCreator (2014-12-09 21:39:59,446)
 */
package models;

import de.metaframe.Revision;

import de.metaframe.jabc.framework.execution.GraphSIBInfo;
import de.metaframe.jabc.framework.sib.annotation.SIBClass;
import de.metaframe.jabc.sib.AbstractGraphSIB;


/**
 * Auto-generated GraphSIBclass.
 *
 * @author isabella
 * @version $Revision: $ $Date: $
 */
@Revision("$Revision: $ $Date: $")
@SIBClass("7389faea-3712-4b0f-8ce6-bc08a39436ad")
@de.metaframe.jabc.framework.sib.annotation.GraphSIB("8d9de7bb-c963-48f7-8087-37d86e9696c5")
public class AddTask extends AbstractGraphSIB {
    //Static branches.
    public final String[] BRANCHES = {  };

    //Parameters.

    /**
     * Default Constructor.
     */
    public AddTask() {
        super();
    }

    /**
    * @see de.metaframe.jabc.sib.AbstractGraphSIB#getGraphSIBInfo()
    */
    public GraphSIBInfo getGraphSIBInfo() {
        return new GraphSIBInfo();
    }
}
