/*
 *  ____ ___ ____   ____   powered by   _
 * / ___|_ _| __ ) / ___|_ __ ___  __ _| |_ ___  _ __
 * \___ \| ||  _ \| |   | '__/ _ \/ _` | __/ _ \| '__|
 *  ___) | || |_) | |___| | |  __/ (_| | || (_) | |
 * |____/___|____/ \____|_|  \___|\__,_|\__\___/|_|
 * Generated by the SIBCreator (2014-12-09 21:41:21,447)
 */
package test;

import de.metaframe.Revision;

import de.metaframe.jabc.framework.execution.GraphSIBInfo;
import de.metaframe.jabc.framework.sib.annotation.SIBClass;
import de.metaframe.jabc.sib.AbstractGraphSIB;


/**
 * Auto-generated GraphSIBclass.
 *
 * @author isabella
 * @version $Revision: $ $Date: $
 */
@Revision("$Revision: $ $Date: $")
@SIBClass("f17101d6-796f-4d6c-9da8-77f6cb5b313f")
@de.metaframe.jabc.framework.sib.annotation.GraphSIB("8d9de7bb-c963-48f7-8087-37d86e9696c5")
public class AddTaskSIB extends AbstractGraphSIB {
    //Static branches.
    public final String[] BRANCHES = {  };

    //Parameters.

    /**
     * Default Constructor.
     */
    public AddTaskSIB() {
        super();
    }

    /**
    * @see de.metaframe.jabc.sib.AbstractGraphSIB#getGraphSIBInfo()
    */
    public GraphSIBInfo getGraphSIBInfo() {
        return new GraphSIBInfo();
    }
}
